### ISSUE TITLE
Error: unable to locate end-of-central-directory record

### ISSUE THREAD

**Issue by brijeshs-atharvasystem** [javanthropus/archive-zip#25]
Hi 

While extracting the zip file, I am getting the below error in some of the zip files

```
Archive::Zip::UnzipError (unable to locate end-of-central-directory record)
/usr/local/bundle/gems/archive-zip-0.12.0/lib/archive/zip.rb:705:in `rescue in find_central_directory'
/usr/local/bundle/gems/archive-zip-0.12.0/lib/archive/zip.rb:678:in `find_central_directory'
/usr/local/bundle/gems/archive-zip-0.12.0/lib/archive/zip.rb:660:in `parse'
/usr/local/bundle/gems/archive-zip-0.12.0/lib/archive/zip.rb:210:in `each'
/usr/local/bundle/gems/archive-zip-0.12.0/lib/archive/zip.rb:576:in `extract'
/usr/local/bundle/gems/archive-zip-0.12.0/lib/archive/zip.rb:100:in `block in extract'
/usr/local/bundle/gems/archive-zip-0.12.0/lib/archive/zip.rb:113:in `open'
/usr/local/bundle/gems/archive-zip-0.12.0/lib/archive/zip.rb:100:in `extract'
```
If I try to extract the same zip file on the machine, it is extracted properly without any issues. 

Note: The error is raised with only a few files. It works fine in other zip files.

**Comment by javanthropus** [comment]
The library attempts to locate a structure located near the end of the zip file that contains the directory of all files in the archive.  It does this by starting at the end of the file and searching backwards for a signature that flags the start of the structure.  Without seeing the zip file in question, I only have a couple guesses as to the problem:

* The file is corrupt or truncated and doesn't have this structure where expected or at all
* The file is a newer zip format than supported by this library

Chances are good that the tool you use on your computer is more robust and is able to support extracting the archive even without this central directory structure.  I've wanted to add the ability to do that to this library but have never found the time.

Are you able to share the problematic zip file?  I can look over the structure if so.

**Comment by brijeshs-atharvasystem** [comment]
Thanks for the reply. 
I can confirm that the file is not corrupt. I am able to unzip the file manually and as also with other zip libaray. I can not share the original file with you but I will try to share the similar file to look into.
